### ISSUE TITLE
java.lang.RuntimeException: ai.onnxruntime.OrtException: Error code - ORT_INVALID_PROTOBUF

### ISSUE THREAD

**Issue by 1512033796** [dnutiu/image-tagger#3]
hi ,D
Why do I call the predictKeywordsForImage method directly in the ModelInference class and execute an error message? My environment is the version of jdk17 and Windows 10

![image](https://github.com/dnutiu/image-tagger/assets/45383053/6079a5d1-dea6-4e71-80b9-5e13c7119d8c)
![image](https://github.com/dnutiu/image-tagger/assets/45383053/06b361ef-51ba-46eb-81a8-0261481cbeaa)

![image](https://github.com/dnutiu/image-tagger/assets/45383053/83477249-4dd6-4134-b8f5-6ae96380970c)

**Comment by dnutiu** [comment]
Hi,

I've tested the program with JDK 17 on Windows 11 64bit. Did you download the latest version?

You can download the model in a separate file: https://github.com/dnutiu/image-tagger/blob/main/image-tagger-core/src/main/resources/model/resnet50.onnx

And call:

```java
environment.createSession("/path-to-model/resnet50.onnx", sessionOptions)
```

If that doesn't work I think it might be a bug in https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime/1.15.1

**Comment by dnutiu** [comment]
Honestly, I'm not so good with Java, if you want to use the model from Python you can use the following code;

Python 3.10.

```python
import os
import onnx

model_path = "C:/Users/nutiu/PycharmProjects/imageKeyworderDataset/dataset/models/resnet50_10_epochs.onnx"

if os.path.exists(model_path):
    print("Model exists")

import torch

torch.cuda.is_available()

# load model categories
categories_path = "C:/Users/nutiu/PycharmProjects/imageKeyworderDataset/dataset/models/categories_resnet50.txt"

with open(categories_path, "r") as f:
    categories = [s.strip() for s in f.readlines()]

print(categories)

import onnxruntime as ort


model_path = "C:/Users/nutiu/PycharmProjects/imageKeyworderDataset/dataset/models/resnet50_10_epochs.onnx"

ort_sess = ort.InferenceSession(model_path, providers=['CPUExecutionProvider'])

# transform image to tensor
import torchvision.transforms as transforms

transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
       mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

from PIL import Image

img = Image.open("C:\\Users\\nutiu\\Desktop\\540A6074.jpg")
x = transform(img)
x = x.unsqueeze(0)  # add batch dimension

# run model
outputs = ort_sess.run(None, {'input.1': x.numpy()})

# get top prediction
import numpy as np

top = np.argmax(outputs)
print(categories[top])

# get top 5 predictions -- sorted from highest to lowest
sorted_predictions = np.argsort(outputs)[0][0][::-1]

for prediction in sorted_predictions:
    value = outputs[0][0][prediction]
    if value < -0.5:
        break
    print(categories[prediction])
```

Requirements:
```
fastai==2.7.12
onnx==1.14.0
onnxruntime==1.14
```

The categories.txt is in the form:

```text
abandoned
abdomen
abstract
abundance
add new keyword
adult
adventure
aerial
``` 

And can be downloadef from: https://github.com/dnutiu/image-tagger/blob/main/image-tagger-core/src/main/java/dev/nuculabs/keyworder/Keywords.java

**Comment by 1512033796** [comment]
> If that doesn't work I think it might be a bug in https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime/1.15.1

The environment used is Windows 10, with JDK version 17, and I have replaced onnxruntime-gpu with onnxruntime. Do you use the dependency of onnxruntime-gpu when running in Windows 11? Do I need to install additional GPU memory to use this dependency?

**Comment by 1512033796** [comment]
> Hi,
> 
> I've tested the program with JDK 17 on Windows 11 64bit. Did you download the latest version?
> 
> You can download the model in a separate file: https://github.com/dnutiu/image-tagger/blob/main/image-tagger-core/src/main/resources/model/resnet50.onnx
> 
> And call:
> 
> ```java
> environment.createSession("/path-to-model/resnet50.onnx", sessionOptions)
> ```

Thank you for your reminder. I have found that the file downloaded using git, resnet50.onnx, cannot be downloaded, so it cannot be run. Additionally, downloading this file separately will suffice! Also, can this algorithm be self-learning? I found that when I identify photos of men with beards, the keyword 'woman' appears

**Comment by dnutiu** [comment]
Hello,

> Also, can this algorithm be self-learning?

You can improve the model by using `transfer learning` I think, but I'm not so sure about it. I've found this on ONNX website: https://onnxruntime.ai/docs/tutorials/on-device-training.html
- https://github.com/microsoft/onnxruntime-training-examples/tree/master/on_device_training

> I found that when I identify photos of men with beards, the keyword 'woman' appears

Yeah, unfortunately I don't have many photos of men with beards that are labeled. I'll need to improve the model and will do so when I'll find the time

**Comment by dnutiu** [comment]
Another option would be to modify the threshold from `-1.11f` to `-0.5f`

**Comment by 1512033796** [comment]
Thank you for your answer. I will try my own model learning and wish you a happy life

**Comment by dnutiu** [comment]
I've started with https://course.fast.ai/ and studied multilabel classification. I trained a Pytorch model then converted it to an ONNX model to use it from Java and other languages.

You are welcome, have a happy life as well!
